name: Update Lotto Data

on:
  schedule:
    - cron: '47 11 * * 6'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: crawl
        run: python scripts/crawl.py
      - name: commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add lotto.json
          git diff --staged --quiet || git commit -m "update"
          git push
